### ISSUE TITLE
Automate Docker Builds when pushing

### ISSUE THREAD

**Issue by amercader** [okfn/website#559]
Docker Hub is dropping free support for Automated Builds, so we will migrate this step to GitHub actions. When we push a new tag to the repo an action should kick in that builds the Docker image and pushes it to the Docker Hub registry.

These actions looks like what we need: https://github.com/marketplace/actions/build-and-push-docker-images
And this configuration should trigger it when pushing a tag, as suggested by @chris48s:

```
name: Build Docker Image
on: create
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      # do the things
```

To authenticate on Docker Hub use the *okibot* docker account. I'll DM an Access Token.
